CRAU-1577 - New Expected AssetDB json files for new XMLs

diff --git a/bin/run-multiple b/bin/run-multiple
--- a/bin/run-multiple
+++ b/bin/run-multiple
@@ -21,22 +21,26 @@ do
 done    
 # EXECUTE
 rm -rf target*
-EXITSTATUS=0
 
 time (for ((THISRUN=1;THISRUN<=$RUNS;THISRUN++))
 do
     echo "======================= RUN:#${THISRUN} - ENV: ${ENV} ======================="
+    export THISRUN=$THISRUN
     rm -f THIS.log
-    mvn clean test -Dkarate.options="-t @${TAG}" -Dkarate.targetEnv="${ENV}" | tee THIS.log
+    mvn clean test -Dkarate.options="-t @${TAG}" -Dkarate.targetEnv="${ENV}" | tee -a THIS.log
     STATUS="PASSED"
     if grep -q "BUILD FAILURE" THIS.log; then
         STATUS="FAILED" # SomeString was found
-        EXITSTATUS=1
     fi
 
     cd "$THIS_CWD"
     cp -r target target_${THISRUN}_${STATUS}
 
 done)
-
-exit $EXITSTATUS
+if grep -q "BUILD FAILURE" THIS.log; then
+    echo "BUILD FAILURE"
+    exit 1
+else
+    echo "BUILD SUCCESS"
+    exit 0
+fi
